spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dftest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone  GMT
    password: a3240124918
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:**/mapper/*.xml
