spring:
  datasource:
    url: jdbc:mysql://localhost:3306/model?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone  GMT
    password: 1020915
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:**/mapper/*.xml
